"""Criando tabela de documentos

Revision ID: 7b89f8bcf374
Revises: 
Create Date: 2024-05-06 22:06:18.076774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b89f8bcf374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_docs',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('children', sa.String(length=3000), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_docs')
    # ### end Alembic commands ###
